name: Boa tests

on:
  # Triggers the workflow on push request events on all branches
  push:
    branches:
      - "**"
  # Triggers the workflow on pull request events on all branches
  pull_request:
    branches:
      - "**"

jobs:
  tests:
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt
    - run: make test
