name: Boa tests

on:
  # Triggers the workflow on push request events on all branches
  push:
    branches:
      - "**"
  # Triggers the workflow on pull request events on all branches
  pull_request:
    branches:
      - "**"

jobs:
  boatest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - run: mkdir -p $HOME/.cache
      - run: make test
        env:
          WEB3_ALCHEMY_API_KEY: ${{ secrets.WEB3_ALCHEMY_API_KEY }}
